default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5

development:
  <<: *default
  database: rails_belt

test:
  <<: *default
  database: rails_belt

production:
  <<: *default
  database: rails_belt