# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04407a55148d4ca2a349f150ff0bcb51d1d1f7fd225e5ca7cdcb45b4b4f0aadb2dc7429f1a5b8c0641749f1fe31222462d7627361313450f101bef11f928395b

test:
  secret_key_base: c74f92c701cebd1952ec8740bf0a6e5fec43b14100739eff989338e0f44396dab1073914e26f5b3041cc266c6a0447291f1a1477f2a995a0238bfff8b2582085

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
